export type LandingLocale = "vi" | "en";

export const landingCopy = {
  vi: {
    skip: "Bỏ qua đến nội dung chính",
    home: "FoodGuard — trang chủ",
    mainNavigation: "Điều hướng chính",
    explore: "Khám phá",
    howItWorks: "Cách hoạt động",
    language: "Ngôn ngữ",
    heroEyebrow: "Marketplace có lớp kiểm chứng",
    heroTitle: "Món ngon đến cửa, bằng chứng đi cùng.",
    heroLede: "Chọn món Việt từ catalog demo, xem trước cam kết món ăn và hiểu cách bằng chứng công khai có thể đi cùng từng đơn.",
    heroAlt: "Bàn món Việt với phở, bánh xèo và cuốn tươi",
    searchLabel: "Tìm món ăn hoặc nhà hàng",
    searchPlaceholder: "Tìm phở, cơm nhà, món chay…",
    searchButton: "Tìm món",
    createOrder: "Tạo đơn qua hợp đồng",
    deployment: "Chưa triển khai contract trên StudioNet — khám phá vẫn sẵn sàng, thao tác hợp đồng đang khóa.",
    catalogEyebrow: "Catalog demo · Phiên bản 1",
    catalogTitle: "Quán Việt đáng để mở thực đơn",
    defaultResults: "Sáu hồ sơ minh họa, mỗi món có dữ liệu đủ để tạo manifest ở bước đặt hàng.",
    categories: "Danh mục món ăn",
    all: "Tất cả",
    results: "Kết quả nhà hàng",
    emptyTitle: "Chưa tìm thấy món phù hợp",
    emptyBody: "Thử từ khóa ngắn hơn hoặc quay lại danh mục “Tất cả”.",
    closingEyebrow: "Rõ giới hạn trước khi bắt đầu",
    closingTitle: "Khám phá món trước. Tin bằng chứng sau khi kiểm tra.",
    closingBody: "FoodGuard không thay nhà hàng, courier hay validator bằng một nhãn “đã xác minh”. Nó minh họa cách giữ nguyên cam kết, theo dõi bằng chứng và chỉ hiển thị kết quả sau khi contract đọc lại trạng thái.",
    footer: "Catalog demo · Bằng chứng công khai · Không lưu khóa riêng.",
  },
  en: {
    skip: "Skip to main content",
    home: "FoodGuard — home",
    mainNavigation: "Main navigation",
    explore: "Explore",
    howItWorks: "How it works",
    language: "Language",
    heroEyebrow: "A marketplace with a verification layer",
    heroTitle: "Good food at your door, evidence alongside.",
    heroLede: "Choose Vietnamese dishes from a demo catalog, review each food commitment, and see how public evidence can travel with an order.",
    heroAlt: "Vietnamese table spread with pho, banh xeo, and fresh rolls",
    searchLabel: "Search dishes or restaurants",
    searchPlaceholder: "Search pho, rice, vegetarian food…",
    searchButton: "Search",
    createOrder: "Create contract order",
    deployment: "No FoodGuard contract is deployed on StudioNet — browsing stays available, while contract actions are locked.",
    catalogEyebrow: "Demo catalog · Version 1",
    catalogTitle: "Vietnamese restaurants worth exploring",
    defaultResults: "Six illustrative profiles, each with enough dish data to create a manifest at checkout.",
    categories: "Food categories",
    all: "All",
    results: "Restaurant results",
    emptyTitle: "No matching dishes yet",
    emptyBody: "Try a shorter search or return to the “All” category.",
    closingEyebrow: "Know the limits before you begin",
    closingTitle: "Discover food first. Trust evidence only after checking it.",
    closingBody: "FoodGuard does not replace restaurants, couriers, or validators with a “verified” label. It demonstrates how commitments can be preserved, evidence tracked, and outcomes shown only after contract state is read back.",
    footer: "Demo catalog · Public evidence · No private keys stored.",
  },
} as const;
